const fontOptions = [
  'Roboto',
  'Open Sans',
  'Noto Sans JP',
  'Montserrat',
  'Lato',
  'Poppins',
  'Roboto Condensed',
  'Source Sans Pro',
  'Inter',
  'Material Icons',
  'Roboto Mono',
  'Oswald',
  'Raleway',
  'Noto Sans',
  'Ubuntu',
  'Roboto Slab',
  'Nunito Sans',
  'Nunito',
  'Playfair Display',
  'Rubik',
  'Merriweather',
  'PT Sans',
  'Noto Sans KR',
  'Kanit',
  'Work Sans',
  'Lora',
  'Fira Sans',
  'Noto Sans TC',
  'Quicksand',
  'Barlow',
  'Mukta',
  'Inconsolata',
  'Mulish',
  'IBM Plex Sans',
  'PT Serif',
  'Titillium Web',
  'Heebo',
  'DM Sans',
  'Noto Serif',
  'Libre Franklin',
  'Manrope',
  'Nanum Gothic',
  'Karla',
  'Hind Siliguri',
  'Josefin Sans',
  'Material Icons Outlined',
  'Arimo',
  'Dosis',
  'Libre Baskerville',
  'PT Sans Narrow',
  'Source Serif Pro',
  'Cairo',
  'Bitter',
  'Bebas Neue',
  'Oxygen',
  'Source Code Pro',
  'Cabin',
  'EB Garamond',
  'Abel',
  'Anton',
  'Dancing Script',
  'Lobster',
  'Prompt',
  'Barlow Condensed',
  'Exo 2',
  'Maven Pro',
  'Hind',
  'Pacifico',
  'Space Grotesk',
  'Comfortaa',
  'Rajdhani',
  'Crimson Text',
  'Signika Negative',
  'Jost',
  'Fjalla One',
  'Noto Sans SC',
  'Varela Round',
  'Teko',
  'Noto Serif JP',
  'Material Icons Round',
  'Material Symbols Outlined',
  'Arvo',
  'Assistant',
  'Asap',
  'Archivo',
  'Merriweather Sans',
  'Caveat',
  'Public Sans',
  'IBM Plex Mono',
  'Slabo 27px',
  'Abril Fatface',
  'Righteous',
  'Shadows Into Light',
  'Tajawal',
  'Satisfy',
  'Overpass',
  'Material Icons Sharp',
  'Fira Sans Condensed',
  'Cormorant Garamond',
  'M PLUS Rounded 1c',
  'Yanone Kaffeesatz',
  'Noto Sans Arabic',
  'Catamaran',
  'Red Hat Display',
  'Barlow Semi Condensed',
  'Indie Flower',
  'Material Icons Two Tone',
  'Asap Condensed',
  'Zilla Slab',
  'Hind Madurai',
  'Nanum Myeongjo',
  'Secular One',
  'Play',
  'Exo',
  'Domine',
  'Questrial',
  'Sarabun',
  'Lilita One',
  'Chakra Petch',
  'IBM Plex Sans Arabic',
  'Signika',
  'Bree Serif',
  'Russo One',
  'Permanent Marker',
  'IBM Plex Serif',
  'Acme',
  'Outfit',
  'M PLUS 1p',
  'Saira Condensed',
  'Material Symbols Rounded',
  'Figtree',
  'Didact Gothic',
  'Vollkorn',
  'Rowdies',
  'Alfa Slab One',
  'Alegreya Sans',
  'Noto Sans HK',
  'Amatic SC',
  'Changa',
  'ABeeZee',
  'DM Serif Display',
  'Cinzel',
  'Archivo Narrow',
  'Kalam',
  'Yantramanav',
  'Cardo',
  'Space Mono',
  'Orbitron',
  'Almarai',
  'Archivo Black',
  'Sora',
  'Urbanist',
  'Tinos',
  'Noticia Text',
  'Zeyada',
  'Alegreya',
  'Frank Ruhl Libre',
  'Lexend',
  'Cormorant',
  'Baloo 2',
  'Martel',
  'Ubuntu Condensed',
  'Great Vibes',
  'Lobster Two',
  'Spectral',
  'PT Sans Caption',
  'Amiri',
  'Patua One',
  'Lexend Deca',
  'Be Vietnam Pro',
  'Courgette',
  'Plus Jakarta Sans',
  'Montserrat Alternates',
  'Noto Serif TC',
  'Prata',
  'Philosopher',
  'Alata',
  'Encode Sans',
  'Crete Round',
  'Francois One',
  'Pathway Gothic One',
  'Titan One',
  'Stint Ultra Condensed',
  'Gruppo',
  'Paytone One',
  'Eczar',
  'Rokkitt',
  'Antonio',
  'Kaushan Script',
  'PT Mono',
  'Passion One',
  'Noto Kufi Arabic',
  'Sen',
  'Noto Serif KR',
  'Sacramento',
  'Bodoni Moda',
  'Old Standard TT',
  'Macondo',
  'Sawarabi Mincho',
  'Gloria Hallelujah',
  'Marcellus',
  'Cookie',
  'Yellowtail',
  'Sawarabi Gothic',
  'Alice',
  'Luckiest Guy',
  'Yeseva One',
  'Staatliches',
  'Creepster',
  'Saira',
  'Khand',
  'News Cycle',
  'Quattrocento Sans',
  'Carter One',
  'Noto Sans Display',
  'Antic Slab',
  'Concert One',
  'El Messiri',
  'Unna',
  'Gothic A1',
  'Press Start 2P',
  'Crimson Pro',
  'Patrick Hand',
  'Commissioner',
  'Chivo',
  'Arsenal',
  'Josefin Slab',
  'Cantarell',
  'Faustina',
  'Cuprum',
  'Roboto Flex',
  'Advent Pro',
  'Fira Sans Extra Condensed',
  'Gelasio',
  'Marck Script',
  'Quattrocento',
  'Ubuntu Mono',
  'Sanchez',
  'Handlee',
  'Poiret One',
  'Mr Dafoe',
  'Vidaloka',
  'Alegreya Sans SC',
  'Neucha',
  'Bangers',
  'Neuton',
  'Unbounded',
  'Merienda',
  'Mukta Malar',
  'IBM Plex Sans Condensed',
  'Mitr',
  'Aleo',
  'Special Elite',
  'Noto Sans Thai',
  'Architects Daughter',
  'Tangerine',
  'Ultra',
  'Ruda',
  'Playfair Display SC',
  'Taviraj',
  'League Spartan',
  'DM Serif Text',
  'Allura',
  'Noto Serif SC',
  'Literata',
  'Gudea',
  'Encode Sans Condensed',
  'Libre Caslon Text',
  'Fugaz One',
  'Hind Vadodara',
  'Amaranth',
  'Parisienne',
  'Days One',
  'Nanum Gothic Coding',
  'Roboto Serif',
  'Ropa Sans',
  'Itim',
  'Tenor Sans',
  'Quantico',
  'Volkhov',
  'Abhaya Libre',
  'Mada',
  'Homemade Apple',
  'Red Hat Text',
  'Viga',
  'Bai Jamjuree',
  'Yatra One',
  'Saira Semi Condensed',
  'Pragati Narrow',
  'Mandali',
  'Oleo Script',
  'Playball',
  'Kosugi Maru',
  'Hammersmith One',
  'Ramabhadra',
  'Blinker',
  'Rock Salt',
  'Readex Pro',
  'Rubik Mono One',
  'Castoro',
  'Istok Web',
  'Source Sans 3',
  'Bungee',
  'Monoton',
  'Alex Brush',
  'Bad Script',
  'Inter Tight',
  'Nanum Pen Script',
  'Laila',
  'Baskervville',
  'Unica One',
  'Epilogue',
  'Jura',
  'Allerta Stencil',
  'Actor',
  'Monda',
  'Fira Mono',
  'Cousine',
  'Noto Serif Bengali',
  'Niramit',
  'Voltaire',
  'Audiowide',
  'Adamina',
  'Padauk',
  'Pontano Sans',
  'BenchNine',
  'Cabin Condensed',
  'Lusitana',
  'Calistoga',
  'Sriracha',
  'Economica',
  'Khula',
  'Pangolin',
  'Alef',
  'Courier Prime',
  'Shrikhand',
  'Jaldi',
  'Sorts Mill Goudy',
  'Rufina',
  'Albert Sans',
  'Damion',
  'Julius Sans One',
  'Kumbh Sans',
  'Athiti',
  'Lalezar',
  'Sigmar One',
  'Nothing You Could Do',
  'Black Ops One',
  'Noto Naskh Arabic',
  'Electrolize',
  'Varela',
  'Sarala',
  'Holtwood One SC',
  'Londrina Solid',
  'Share Tech Mono',
  'Comic Neue',
  'Anonymous Pro',
  'Palanquin',
  'Pinyon Script',
  'Krub',
  'Forum',
  'Martel Sans',
  'Sintony',
  'Italianno',
  'Karma',
  'Squada One',
  'Hind Guntur',
  'Black Han Sans',
  'Gochi Hand',
  'Sansita',
  'Noto Sans Tamil',
  'Zen Kaku Gothic New',
  'VT323',
  'Cabin Sketch',
  'Lemonada',
  'Glegoo',
  'Pridi',
  'Gilda Display',
  'Syne',
  'Leckerli One',
  'Six Caps',
  'Covered By Your Grace',
  'JetBrains Mono',
  'Koulen',
  'Mate',
  'Zen Maru Gothic',
  'Reenie Beanie',
  'Boogaloo',
  'Arapey',
  'Chewy',
  'Libre Barcode 39',
  'Cutive Mono',
  'Noto Sans Malayalam',
  'Kreon',
  'Fraunces',
  'Just Another Hand',
  'Aclonica',
  'Shippori Mincho',
  'Kosugi',
  'Syncopate',
  'Caveat Brush',
  'Shadows Into Light Two',
  'Noto Sans Mono',
  'PT Serif Caption',
  'DM Mono',
  'Nanum Brush Script',
  'Goldman',
  'Telex',
  'Atkinson Hyperlegible',
  'Carrois Gothic',
  'Berkshire Swash',
  'Cantata One',
  'Basic',
  'Charm',
  'Michroma',
  'Mali',
  'Rancho',
  'Mrs Saint Delafield',
  'Aldrich',
  'Amita',
  'Armata',
  'Short Stack',
  'Lustria',
  'Palanquin Dark',
  'Saira Extra Condensed',
  'Mate SC',
  'Candal',
  'Herr Von Muellerhoff',
  'Cinzel Decorative',
  'Livvic',
  'Averia Serif Libre',
  'Coda',
  'Pattaya',
  'Noto Color Emoji',
  'Fira Code',
  'Corben',
  'Overpass Mono',
  'Racing Sans One',
  'Oranienbaum',
  'Alumni Sans',
  'Jua',
  'Fredericka the Great',
  'Alatsi',
  'Big Shoulders Display',
  'Source Serif 4',
  'Reem Kufi',
  'Capriola',
  'Average Sans',
  'Julee',
  'Alike',
  'La Belle Aurore',
  'STIX Two Text',
  'Bevan',
  'Wallpoet',
  'GFS Didot',
  'Antic',
  'Petrona',
  'Rammetto One',
  'Do Hyeon',
  'Oxanium',
  'Annie Use Your Telescope',
  'Arbutus Slab',
  'Belleza',
  'Cedarville Cursive',
  'Knewave',
  'Chonburi',
  'Arizonia',
  'Yrsa',
  'Marcellus SC',
  'Noto Serif Display',
  'Changa One',
  'Balsamiq Sans',
  'Noto Sans Devanagari',
  'Newsreader',
  'K2D',
  'BioRhyme',
  'Darker Grotesque',
  'Allerta',
  'Graduate',
  'Krona One',
  'Overlock',
  'Rozha One',
  'Quintessential',
  'Suez One',
  'Sofia',
  'Enriqueta',
  'Kameron',
  'BIZ UDPGothic',
  'Rye',
  'Noto Sans Hebrew',
  'Trirong',
  'Cormorant Infant',
  'Bungee Inline',
  'Norican',
  'Scada',
  'Markazi Text',
  'Coming Soon',
  'Rambla',
  'IBM Plex Sans Thai',
];

const fontSelect = document.getElementById('font-select');

fontOptions.forEach((option) => {
  let newOption = document.createElement('option');
  newOption.text = option;
  fontSelect.add(newOption);
});
